name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on pull request events
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    name: '🕵️‍♂️ Lint'
    runs-on: ubuntu-latest
    container: node

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          check-latest: true

      - name: Install dependencies
        run: npm ci --no-optional --no-audit --prefer-offline --progress=false

      - name: Verify code style
        run: npm run lint
